import json
import logging
from pathlib import Path
from datetime import datetime
import traceback

def setup_eseas_logger(name="eseas_error_logger", filename="failed_runs.log", level=logging.ERROR):
    cwd = Path.cwd()
    eseas_dir = cwd / ".eseas"
    logs_dir = eseas_dir / ".logs"
    
    logs_dir.mkdir(parents=True, exist_ok=True)
    
    example_script = eseas_dir / "quick_start_example.py"
    if not example_script.exists():
        example_content = r"""from eseas import Options, Seasonal

def main():
    options = Options(
        demetra_source_folder=r"C:\Data\your_demetra_xmls",
        local_folder=r"C:\Data\eseas_outputs", 
        auto_download=True,
        auto_approve=False
    )
    
    seas = Seasonal(options)
    seas.run()

if __name__ == "__main__":
    main()
"""
        try:
            example_script.write_text(example_content, encoding='utf-8')
        except Exception:
            pass

    readme_file = eseas_dir / "README.txt"
    if not readme_file.exists():
        readme_content = """This .eseas directory is automatically generated by the eseas package.
It contains diagnostic logs in the .logs/ folder to assist with troubleshooting.
"""
        try:
            readme_file.write_text(readme_content, encoding='utf-8')
        except Exception:
            pass
            
    logger = logging.getLogger(name)
    if not logger.handlers:
        logger.setLevel(level)
        
        log_file = logs_dir / filename
        handler = logging.FileHandler(log_file, encoding='utf-8')
        handler.setLevel(level)
        
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        handler.setFormatter(formatter)
        
        logger.addHandler(handler)
        
    return logger

def get_paths_info():
    paths = {}
    try:
        from .cruncher_classes import get_cruncher
        from .create_bat_command import get_demetra_type
        
        cruncher = get_cruncher()
        ws = cruncher.local_work_space
        paths["local_workspace"] = str(ws)
        paths["demetra_folder"] = str(cruncher.demetra_folder)
        paths["cruncher_folder"] = str(cruncher.crunch_folder)
        paths["general_params"] = str(Path(ws) / "general.params")
        try:
            paths["execution_script"] = str(get_demetra_type().demetra_command_file_name())
        except Exception:
            paths["execution_script"] = "Could not resolve"
            
        # check script content
        try:
            exec_path = Path(paths["execution_script"])
            if exec_path.exists():
                paths["script_content"] = exec_path.read_text(encoding="utf-8")
        except Exception:
            pass
            
    except Exception as e:
        paths["error"] = f"Could not resolve workspace paths: {e}"
        
    return paths

def log_eseas_run(status: str, error_msg: str=None, options=None):
    try:
        from .. import __version__
        eseas_version = __version__
    except ImportError:
        try:
            import importlib.metadata
            eseas_version = importlib.metadata.version('eseas')
        except Exception:
            eseas_version = "Unknown"
        
    if status == "success":
        logger = setup_eseas_logger(name="eseas_success_logger", filename="last_good_run.log", level=logging.INFO)
    else:
        logger = setup_eseas_logger()
        
    options_dict = {}
    if options:
        try:
            if hasattr(options, "__dict__"):
                for k, v in options.__dict__.items():
                    options_dict[k] = str(v)
            else:
                options_dict = {"repr": repr(options)}
        except Exception:
            options_dict = {"repr": "Could not parse options."}

    paths_info = get_paths_info()

    log_data = {
        "status": status,
        "eseas_version": eseas_version,
        "options": options_dict,
        "paths": paths_info
    }
    
    if error_msg:
        log_data["error"] = str(error_msg)
    
    if status == "success":
        logger.info(json.dumps(log_data, indent=2))
    else:
        logger.error(json.dumps(log_data, indent=2))

def log_eseas_error(error_msg: str, options=None):
    log_eseas_run("error", error_msg=error_msg, options=options)

def log_eseas_success(options=None):
    log_eseas_run("success", options=options)

