name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install uv evdspy  

          # Create virtual environment and activate it
          uv venv
          source .venv/bin/activate
          uv pip install .

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install uv evdspy

          # Create virtual environment
          uv venv
          
          # Activate virtual environment
          .venv\Scripts\activate

          # Install dependencies inside the virtual environment
          uv pip install .

      - name: Run tests
        run: pytest
